### ISSUE TITLE
Fresh app can't `yarn install`

### ISSUE THREAD

**Issue by jorgtz** [infinitered/ignite#2750]
### Describe the bug

After running the command 

`npx ignite-cli@latest new PizzaApp`
And successfully finish. Then I `cd` into the app folder and run `yarn install`. Then the following error appears:
```
success Saved lockfile.
$ patch-package
patch-package 8.0.0
Applying patches...
Error: Patch file found for package react-native-drawer-layout which is not present at node_modules/react-native-drawer-layout
---
patch-package finished with 1 error(s).
✨  Done in 28.40s
```
I have tested with node versions 18 and 20.

How can I solve this issue?

### Ignite version

9.8.2

### Additional info

Need to install the following packages:
ignite-cli@9.8.2
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
System
  platform           darwin
  arch               arm64
  cpu                16 cores     Apple M3 Max
  directory          PizzaApp     /Users/user/Dev/Mobile/NewApp/PizzaApp

JavaScript (and globally-installed packages)
  node               20.16.0      /Users/user/.nvm/versions/node/v20.16.0/bin/node
  npm                10.8.1       /Users/user/.nvm/versions/node/v20.16.0/bin/npm
    corepack         0.28.2
    npm              10.8.1
  yarn               1.22.22      /opt/homebrew/bin/yarn
  pnpm               -            not installed
  bun                -            not installed
  expo               51.0.28      managed

Ignite
  ignite-cli         9.8.2        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               17.0.12      /usr/bin/java
  android home       -            /Users/user/Library/Android/sdk

iOS
  xcode              15.4
  cocoapods          1.15.2       /opt/homebrew/bin/pod

Tools
  git                git version 2.39.3 (Apple Git-146)   /usr/bin/git

**Comment by leonskim** [comment]
Hi! This should be fixed by https://github.com/infinitered/ignite/pull/2736. You can try with `master` branch or apply the changes in the PR until we release a new version. I'm going to close this issue but feel free to reopen if that doesn't help. :+1:

**Comment by jorgtz** [comment]
> Hi! This should be fixed by #2736. You can try with `master` branch or apply the changes from the PR until we release a new version. I'm going to close this issue but feel free to reopen if that doesn't help. 👍

Thank you for your response, can you please tell me how can I achieve that? I haven't found that on the documentation.
How can use `master` instead of `latest` version ? 

Thanks in advanced

**Comment by leonskim** [comment]
@jorgtz  No worries! You can achieve that by these steps:

1. `git clone https://github.com/infinitered/ignite.git`
2. `cd ignite`
3. `yarn install`
4. `cd ..`
5. `./ignite/bin/ignite new PizzaApp`

After running all the commands, you will have `PizzaApp`, and now you can run it.

6. `cd PizzaApp`
7. `yarn ios` or `yarn android`

Hope you can ignite your project this time!

**Comment by jorgtz** [comment]
@leonskim thanks for the instructions. I have done what you pointed me, but unfornunately the error persist.
I had to manually delete the `patches/react-native-drawer-layout+4.0.0-alpha.9.patc` to fix the error.

Thanks again :)
